### ISSUE TITLE
Consistent nomenclature

### ISSUE THREAD

**Issue by gvolpe** [cr-org/neutron#27]
The nomenclature we have at the moment is quite inconsistent. We have `Consumer` and `Publisher` but I think we should have one of the following options: 

[![](https://api.gh-polls.com/poll/01EAA5RDK419VV4X508BSFM24M/%60Consumer%60%20and%20%60Producer%60%20%20)](https://api.gh-polls.com/poll/01EAA5RDK419VV4X508BSFM24M/%60Consumer%60%20and%20%60Producer%60%20%20/vote)
[![](https://api.gh-polls.com/poll/01EAA5RDK419VV4X508BSFM24M/%60Subscriber%60%20and%20%60Publisher%60)](https://api.gh-polls.com/poll/01EAA5RDK419VV4X508BSFM24M/%60Subscriber%60%20and%20%60Publisher%60/vote)

Let's pick one! :)

For more information, the Pulsar Java API we wrap, uses `Consumer` and `Producer`.

**Comment by psisoyev** [comment]
I would stick to the [official naming](http://pulsar.apache.org/docs/en/concepts-messaging/#producers) to avoid confusion
